// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealtimeMarketData.Infrastructure.Persistence;

#nullable disable

namespace RealtimeMarketData.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321105108_NormalizeWindowDatesToUtcTicks")]
    partial class NormalizeWindowDatesToUtcTicks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RealtimeMarketData.Domain.Aggregates.PriceWindow.PriceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.Property<long>("WindowEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long>("WindowStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "WindowStart")
                        .IsUnique()
                        .HasDatabaseName("IX_PriceWindows_Symbol_WindowStart");

                    b.ToTable("PriceWindows", (string)null);
                });

            modelBuilder.Entity("RealtimeMarketData.Infrastructure.Persistence.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.ToTable("ApiKeys", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1184e52-34f7-4fa6-a6f7-1903cf65b1d4"),
                            CreatedOn = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            KeyId = "seed_default",
                            Name = "Default seeded client",
                            SecretHash = "298754DB2DBAB6EC62605CEB0379EB7EE376580359449EFE0CAA3AA06CD56736"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
